ruby:
  enabled: true

python:
  enabled: true

coffeescript:
  enabled: true
  config_file: coffeelint.json

eslint:
  enabled: true
  config_file: .eslintrc.yml

jshint:
  enabled: false

haml:
  enabled: true

scss:
  enabled: true
