export const TOGGLE_ABOUT = "TOGGLE_ABOUT"

export const ADD_ENTITY = "ADD_ENTITY"

export const FETCH_ENTITIES = "FETCH_ENTITIES"
export const FETCH_ENTITIES_PENDING = "FETCH_ENTITIES_PENDING"
export const FETCH_ENTITIES_FULFILLED = "FETCH_ENTITIES_FULFILLED"
export const FETCH_ENTITIES_REJECTED = "FETCH_ENTITIES_REJECTED"
