# Avoid warnings about the git protocol being insecure when using github repos.
# https://github.com/bundler/bundler/issues/4978
#https://github.com/twbs/bootstrap-rubygem
source 'https://rubygems.org'
source 'https://rails-assets.org' do
    gem 'rails-assets-tether', '>= 1.1.0'
end
# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.0.0', '>= 5.0.0.1'
# Use postgresql as the database for Active Record
gem 'pg', '~> 0.18'
# Use Puma as the app server
gem 'puma', '~> 3.0'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

gem "passenger", ">= 5.0.25", require: "phusion_passenger/rack_handler"
gem 'draper', "3.0.0.pre1"

gem 'bootstrap', '~> 4.0.0.alpha4'
gem 'haml-rails'
gem 'country_select'
gem 'kaminari'
gem "htmlentities"
gem 'active_model_serializers', '~> 0.10.0'
gem 'activemodel-serializers-xml'
gem 'swagger-blocks'
gem 'jsonapi-resources'
gem 'rack-cors', :require => 'rack/cors'

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console'
  gem 'listen', '~> 3.0.5'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development
  gem 'capistrano', '~> 3.6'
  gem 'capistrano-rails', '~> 1.1'
  gem 'capistrano-bundler', '~> 1.1.2'
  gem 'capistrano-passenger'
  gem 'railroady'
  gem 'rvm1-capistrano3', require: false
  gem 'git'
  gem 'spring-commands-rspec'
  gem 'spring-commands-cucumber'
  #gem 'capistrano-git-submodule-strategy', '~> 0.1', :github => 'ekho/capistrano-git-submodule-strategy'
end

group :development, :test do
  gem 'byebug', platform: :mri
  gem 'mailcatcher'
  gem 'syntax'
  gem 'rspec-rails'
  gem 'rspec-activemodel-mocks'
  gem 'cucumber-rails', require: false
  gem 'awesome_print'
  gem 'webmock'
  gem 'faraday'
  gem 'jsonpath'
  gem 'factory_girl_rails'
end

group :test do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'shoulda'
  gem 'shoulda-matchers'
  gem 'launchy'
  gem 'selenium-webdriver'
  gem 'email_spec'
  gem 'site_prism'
  gem 'poltergeist'
  gem 'rails-controller-testing'
end

